name: Prison
main: com.errol.Main
version: 0.02
author: Errol
softdepend: [Vault] 
commands:
  prison:
    description: all commands prison
    usage: /prison
  pay:
    description: pay someone money
    usage: /pay [username] [amount]
  rank:
    description: look at rank
    usage: /rank
  rankup:
    description: rankup
    usage: /rankup
  prestige:
    description: prestige
    usage: /prestige
  tpay:
    description: pay someone tokens
    usage: /tpay [username] [amount]
  setmoney:
    description: sets someones money
    usage: /setmoney [username] [amount]
  addmoney:
    description: adds someones money
    usage: /addmoney [username] [amount]
  takemoney:
    description: takes someones money
    usage: /addmoney [username] [amount]
  bal:
    description: gets balance of player
    usage: /bal [username]
  mine:
    description: base command for mines
    usage: /mine
  sell:
    description: command for selling
    usage: /sell
  sellall:
    description: command for selling all
    usage: /sellall
   